[project]
name = "elvax-nodes"
version = "1.0.2"
description = """Convenience nodes for ComfyUI!

- LLM TURBO: Run local LLMs faster, directly in ComfyUI
- Load and crop images faster in one node
- Upscale, interpolate, and add film grain in one node
- Tidy workflows with Dynamic Pipes, supporting Set/Get nodes and reroutes

And more..."""
license = { file = "LICENSE" }
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.urls]
Repository = "https://github.com/younestft/Elvax-nodes"
"Bug Tracker" = "https://github.com/younestft/Elvax-nodes/issues"

[tool.comfy]
PublisherId = "elvaxorn"
DisplayName = "Elvax Nodes"
